config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'
  resources :pages
  resources :assets
  resources :user_sessions
  resources :users
  resources :password_resets

  get 'edit_password_reset' => 'password_resets#edit'

  get 'oauths/oauth'

  get 'oauths/callback'

    get 'upload' => 'assets#new', :as => :upload
    get 'signup' => 'users#new', :as => :signup
    get 'login' => 'user_sessions#new', :as => :login
    post 'logout' => 'user_sessions#destroy', :as => :logout

    post "oauth/callback" => "oauths#callback"
    get "oauth/callback" => "oauths#callback" # for use with Github, Facebook
    get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

    get "image" => Dragonfly.app.endpoint { |params, app|
    app.fetch_file("some/dir/#{params[:file]}").thumb(params[:size])
    }

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery! do |config|
      config.authentications_class = Authentication
  end

  validates :password, length: { minimum: 8 }
  validates :password, confirmation: true
  validates :password_confirmation, presence: true
  validates :email, uniqueness: true

  has_many :authentications, :dependent => :destroy
  accepts_nested_attributes_for :authentications
  has_many :assets, :dependent => :destroy
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_filter :require_login, only: [:index, :new, :create]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    @user = User.new
    @asset = Asset.new
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save

          # Sends email to user when user is created.
        format.html { UserMailer.registration_email(@user).deliver_now }
        redirect_to(:users, notice: '已成功登記')
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: '已成功修改' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: '用戶已被取消' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :authentications_attributes)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= simple_form_for @user, html: { id: "signup-form" } do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label "姓" %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label "名" %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label "電郵" %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
   <%= f.label "密碼" %><br />
   <%= f.password_field :password %>
  </div>
  <div class="field">
     <%= f.label "確認密碼" %><br />
     <%= f.password_field :password_confirmation %>
  </div>
  <% if logged_in? %>
      <div class="actions">
        <%= f.submit "修改" %>
      </div>
  <% else %>
      <div class="actions">
        <%= f.submit "登記" %>
      </div>
  <% end %>

  <%= link_to 'Facebook登入', auth_at_provider_path(:provider => :facebook) %>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>First Name</th>
      <th>Last Name</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
      </tr>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>
<p>
  <strong>First Name:</strong>
  <%= @user.first_name %>
</p>
<p>
  <strong>Last Name:</strong>
  <%= @user.last_name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>