config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'
  resources :pages
  resources :assets
  resources :user_sessions
  resources :users
  resources :password_resets

  get 'edit_password_reset' => 'password_resets#edit'

  get 'oauths/oauth'

  get 'oauths/callback'

    get 'upload' => 'assets#new', :as => :upload
    get 'signup' => 'users#new', :as => :signup
    get 'login' => 'user_sessions#new', :as => :login
    post 'logout' => 'user_sessions#destroy', :as => :logout

    post "oauth/callback" => "oauths#callback"
    get "oauth/callback" => "oauths#callback" # for use with Github, Facebook
    get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

    get "image" => Dragonfly.app.endpoint { |params, app|
    app.fetch_file("some/dir/#{params[:file]}").thumb(params[:size])
    }

end

app/models/asset.rb
class Asset < ActiveRecord::Base
    dragonfly_accessor :asset
    validates :asset, presence: true
    belongs_to :user
end

app/controllers/assets_controller.rb
class AssetsController < ApplicationController
  before_action :set_asset, only: [:show, :edit, :update, :destroy]

  # GET /assets
  # GET /assets.json
  def index
    @assets = Asset.all
    @asset = Asset.new
    @user = current_user
  end

  # GET /assets/1
  # GET /assets/1.json
  def show
    @user = current_user
  end

  # GET /assets/new
  def new
    @asset = current_user.assets.build
    @user = current_user
  end

  # GET /assets/1/edit
  def edit
    @user = current_user
  end

  # POST /assets
  # POST /assets.json
  def create
    @asset = current_user.assets.build(asset_params)

    respond_to do |format|
      if @asset.save
        format.html { redirect_to @asset, notice: '已上傳' }
        format.json { render :show, status: :created, location: @asset }
      else
        format.html { render :new }
        format.json { render json: @asset.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assets/1
  # PATCH/PUT /assets/1.json
  def update
    respond_to do |format|
      if @asset.update(asset_params)
        format.html { redirect_to @asset, notice: '已更新' }
        format.json { render :show, status: :ok, location: @asset }
      else
        format.html { render :edit }
        format.json { render json: @asset.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assets/1
  # DELETE /assets/1.json
  def destroy
    @asset.destroy
    respond_to do |format|
      format.html { redirect_to assets_url, notice: '上傳失敗' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_asset
      @asset = Asset.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def asset_params
      params.require(:asset).permit(:asset)
    end
end

app/helpers/assets_helper.rb
module AssetsHelper
end

app/views/assets/_form.html.erb
<!-- asset upload form -->

<%= simple_form_for @asset do |f| %>
  <% if @asset.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@asset.errors.count, "error") %> prohibited this asset from being saved:</h2>

      <ul>
      <% @asset.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "標題" %><br>
    <%= f.text_field :asset_title %>
  </div>
  <div class="field">
    <%= f.label "檔案" %><br>
    <%= f.file_field :asset %>
    <% if f.object.asset_stored? %>
        <%= image_tag f.object.asset.url %>
        <em>Current image</em>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit "上傳" %>
  </div>
<% end %>

app/views/assets/edit.html.erb
<h1>Editing Asset</h1>

<%= render 'form' %>

<%= link_to 'Show', @asset %> |
<%= link_to 'Back', assets_path %>

app/views/assets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Assets</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @assets.each do |asset| %>
      <tr>
        <td><%= asset.asset_title %></td>
        <td><%= link_to image_tag(asset.asset.thumb('150x150#').url), asset %></td>
        <td><%= link_to 'Edit', edit_asset_path(asset) %></td>
        <td><%= link_to 'Destroy', asset, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Asset', new_asset_path %>

app/views/assets/new.html.erb
<div class="flex-container">
    <h3>上傳檔案</h3>

    <%= render 'form' %>

    <%= link_to 'Back', assets_path %>
</div>

app/views/assets/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag @asset.asset.thumb('300x300#').url if @asset.asset_stored? %>
<%= link_to 'Edit', edit_asset_path(@asset) %> |
<%= link_to 'Back', assets_path %>
<p>
  <strong>Title:</strong>
  <%= @asset.asset_title %>
  <%= @asset.user.first_name %>
</p>