config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'
  resources :pages
  resources :assets
  resources :user_sessions
  resources :users
  resources :password_resets

  get 'edit_password_reset' => 'password_resets#edit'

  get 'oauths/oauth'

  get 'oauths/callback'

    get 'upload' => 'assets#new', :as => :upload
    get 'signup' => 'users#new', :as => :signup
    get 'login' => 'user_sessions#new', :as => :login
    post 'logout' => 'user_sessions#destroy', :as => :logout

    post "oauth/callback" => "oauths#callback"
    get "oauth/callback" => "oauths#callback" # for use with Github, Facebook
    get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

    get "image" => Dragonfly.app.endpoint { |params, app|
    app.fetch_file("some/dir/#{params[:file]}").thumb(params[:size])
    }

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
    skip_before_filter :require_login, except: [:destroy]
  def new
    @user = User.new
  end

  def create
    if @user = login(params[:email], params[:password], params[:remember])
      redirect_back_or_to(:users, notice: '已登入')
    else
      flash.now[:alert] = '登入失敗'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to(:users, notice: '已登出')
  end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/_forgot_password_form.html.erb
<%= form_tag password_resets_path, :method => :post do %>
  <div class="field">
    <%= label_tag :email %><br />
    <%= text_field_tag :email %> <%= submit_tag "Reset my password!" %>
  </div>
<% end %>

app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, :id => 'login-form', :method => :post do %>
  <div class="field">
    <%= label_tag "電郵" %><br />
    <%= text_field_tag :email %>
  </div>
  <div class="field">
    <%= label_tag "密碼" %><br />
    <%= password_field_tag :password %>
  </div>
  <div class="field">
    <%= check_box_tag :remember_me, 1, params[:remember_me] %>
    <%= label_tag "記住我" %>
  </div>
  <div class="actions">
    <%= submit_tag "登入" %>
  </div>
  <%= link_to 'Facebook登入', auth_at_provider_path(:provider => :facebook) %>
<% end %>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<h1>Login</h1>

<%= render 'form' %>

<h1>Forgot Password?</h1>
<%= render 'forgot_password_form' %>

<%= link_to 'Back', users_path %>